name: Deploy React Project to Host

on:
  push:
    branches:
      - main # نام شاخه‌ای که می‌خواهید با پوش کردن روی آن، هاست آپدیت شود (مثلاً main یا master)

jobs:
  web-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20 # نسخه نود جی اس پروژه شما

    - name: Install dependencies
      run: npm install

    - name: Build Project
      run: npm run build

    - name: Sync files to Host via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./build/ # پوشه خروجی ری‌اکت
        server-dir: /public_html/ # مسیر پوشه سایت در هاست شما (مثلاً /public_html/)
